services:
  db:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: lab1db_owner
      POSTGRES_PASSWORD: lab1db_password
      POSTGRES_DB: lab1db
    volumes:
      - .:/workspace
      - ./init:/docker-entrypoint-initdb.d
      - ./исходные данные:/data
